version: '3'

services:
  # Backend service
  backend:
    build: ./  # Assuming your backend is in the root directory
    ports:
      - "5000:5000"
    environment:
      - CONNECTION_URL=mongodb://mongodb:27017/test
      - PORT=5000
    depends_on:
      - mongodb
    restart: always

  # Frontend service (you'll need to create a React frontend)
  frontend:
    build: ./client  # Assuming your frontend is in a /client directory
    ports:
      - "3000:3000"
    depends_on:
      - backend

  # MongoDB service
  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    restart: always

volumes:
  mongo-data: 